### ISSUE TITLE
SoundPhysics crashes game on joining server

### ISSUE THREAD

**Issue by Aninuscsalas** [Vidanox/WynncraftEnhanced#2]
> [21:44:15] [Sound engine/ERROR]: Uncaught exception in thread "Sound engine"
java.lang.NoSuchMethodError: 'net.minecraft.class_1959 net.minecraft.class_638.method_23753(net.minecraft.class_2338)'
	at com.sonicether.soundphysics.ALstuff.SPEfx.getAbsorptionHF(SPEfx.java:103) ~[soundphysics-0.5.5.jar:?]
	at com.sonicether.soundphysics.ALstuff.SPEfx.setEnvironment(SPEfx.java:75) ~[soundphysics-0.5.5.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.evaluateEnvironment(SoundPhysics.java:117) ~[soundphysics-0.5.5.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.onPlaySoundReverb(SoundPhysics.java:81) ~[soundphysics-0.5.5.jar:?]
	at net.minecraft.class_4224.handler$cka000$OnPlaySoundInjector(class_4224.java:533) ~[client-intermediary.jar:?]
	at net.minecraft.class_4224.method_19650(class_4224.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_19752(class_1140.java:452) ~[client-intermediary.jar:?]
	at net.minecraft.class_4235$class_4236.method_19737(class_4235.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_4238.method_19765(class_4238.java:42) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Vidanox** [comment]
fixed in 0.3
